// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB00VSaOA455YQFG2i5LDVSofCVYN5kQhE',
    appId: '1:791475807936:web:ba8fb72c822591ee4b6f25',
    messagingSenderId: '791475807936',
    projectId: 'restaurantapptutor',
    authDomain: 'restaurantapptutor.firebaseapp.com',
    storageBucket: 'restaurantapptutor.appspot.com',
    measurementId: 'G-MT3Y9KWT6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSObJprgKbBWYYeDGgexPXQVM8rEGgjpY',
    appId: '1:791475807936:android:6481cfbb511edcd74b6f25',
    messagingSenderId: '791475807936',
    projectId: 'restaurantapptutor',
    storageBucket: 'restaurantapptutor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6-VLjO4ZkamXggEVVwVNavGPpjQntugg',
    appId: '1:791475807936:ios:06a8ce228eb35b614b6f25',
    messagingSenderId: '791475807936',
    projectId: 'restaurantapptutor',
    storageBucket: 'restaurantapptutor.appspot.com',
    iosBundleId: 'com.example.flutterFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6-VLjO4ZkamXggEVVwVNavGPpjQntugg',
    appId: '1:791475807936:ios:06a8ce228eb35b614b6f25',
    messagingSenderId: '791475807936',
    projectId: 'restaurantapptutor',
    storageBucket: 'restaurantapptutor.appspot.com',
    iosBundleId: 'com.example.flutterFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB00VSaOA455YQFG2i5LDVSofCVYN5kQhE',
    appId: '1:791475807936:web:f2ae276b3016f8f24b6f25',
    messagingSenderId: '791475807936',
    projectId: 'restaurantapptutor',
    authDomain: 'restaurantapptutor.firebaseapp.com',
    storageBucket: 'restaurantapptutor.appspot.com',
    measurementId: 'G-XDR3BK7XQ4',
  );

}